name: workout_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: 3.35.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1

  # Annotations for Freezed & JSON
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

  # Local storage
  isar_community: 3.3.0-dev.1
  isar_community_flutter_libs: 3.3.0-dev.1
  path_provider: ^2.1.2

  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.11
  freezed: 2.5.8
  json_serializable: ^6.7.1

  # Isar generator
  isar_community_generator: 3.3.0-dev.1

flutter:
  assets:
    - lib/core/assets/images/
    - lib/core/assets/icons/